name: Format Check, Lint Check and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          check-latest: true

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run unit tests
        run: yarn test

      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile
